<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="mini_footer">
<div class="payment">
<ul>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\v1.png" /></a></li>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\v2.png" /></a></li>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\v3.png" /></a></li>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\v4.png" /></a></li>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\v5.png" /></a></li>
</ul>
</div>
<small class="copyright">
    <span><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
</small>
<div class="social">
<ul>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\s-1.png" /> </a></li>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\s-2.png" /></a></li>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\s-3.png" /></a></li>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\s-4.png" /></a></li>
<li><a href="#"><img src="<?php echo $this->getBaseUrl();?>pub\media\wysiwyg\images\s-5.png" /></a></li>
</ul>
</div>
</div>
